"""add nationwide fuel price

Revision ID: e7eef413ad8e
Revises: dd0c3126d66e
Create Date: 2026-08-10 17:42:30.626494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7eef413ad8e'
down_revision: Union[str, Sequence[str], None] = 'dd0c3126d66e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nationwide_fuel_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unleaded_92', sa.Float(), nullable=False),
    sa.Column('unleaded_95', sa.Float(), nullable=False),
    sa.Column('unleaded_98', sa.Float(), nullable=False),
    sa.Column('super_diesel', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_start', 'period_end', name='uq_nationwide_fuel_price_period')
    )
    op.create_index(op.f('ix_nationwide_fuel_price_period_end'), 'nationwide_fuel_price', ['period_end'], unique=False)
    op.create_index(op.f('ix_nationwide_fuel_price_period_start'), 'nationwide_fuel_price', ['period_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nationwide_fuel_price_period_start'), table_name='nationwide_fuel_price')
    op.drop_index(op.f('ix_nationwide_fuel_price_period_end'), table_name='nationwide_fuel_price')
    op.drop_table('nationwide_fuel_price')
    # ### end Alembic commands ###
